DROP TABLE IF EXISTS Repositories;

CREATE TABLE IF NOT EXISTS Repositories(
    owner VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    visibility ENUM('public', 'private') NOT NULL,
    description TEXT,
    website VARCHAR(1000),
    PRIMARY KEY(owner, name),
    FOREIGN KEY(owner) REFERENCES Users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO Repositories (owner, name, visibility, description, website)
VALUES
('ajakubowicz1j', 'Stim', 'public', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 'https://mapy.cz/pretium/nisl/ut/volutpat/sapien.jsp'),
('sjillett1p', 'Voltsillam', 'private', null, null),
('lcutridge22', 'Opela', 'public', 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 'http://hugedomains.com/nullam/sit/amet/turpis/elementum/ligula/vehicula.aspx'),
('mcorriso', 'Stringtough', 'private', null, 'http://irs.gov/rhoncus/mauris/enim/leo/rhoncus/sed.xml'),
('mmelland1h', 'Cardguard', 'public', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', 'http://moonfruit.com/ullamcorper/augue/a/suscipit/nulla/elit/ac.jsp'),
('cmittene', 'Biodex', 'public', 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', null),
('edumini2d', 'Bitchip', 'private', 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor', 'https://admin.ch/mauris/laoreet.jpg'),
('noffai', 'Fix San', 'private', null, null),
('etampion1b', 'Kanlam', 'private', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 'https://wisc.edu/proin/eu/mi/nulla/ac/enim.png'),
('shatt2k', 'Sub-Ex', 'public', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', null),
('eyabsley12', 'Transcof', 'public', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', 'http://princeton.edu/pede/justo/eu/massa.jsp'),
('eknowlson1g', 'Latlux', 'public', 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 'https://mit.edu/lobortis/est/phasellus/sit/amet.html'),
('ashelley6', 'Kanlam', 'private', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 'https://tinypic.com/ac/consequat/metus/sapien/ut.jsp'),
('jadamef', 'Solarbreeze', 'private', null, 'http://prnewswire.com/eros/viverra/eget/congue/eget.html'),
('shatt2k', 'Latlux', 'private', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 'https://xrea.com/pulvinar.jpg'),
('fgollin1e', 'Namfix', 'private', null, null),
('gmidgley1a', 'Opela', 'public', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 'http://lycos.com/nisl/ut/volutpat.jpg'),
('cteal2p', 'Mat Lam Tam', 'public', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 'http://auda.org.au/sed/justo/pellentesque/viverra/pede/ac/diam.aspx'),
('gsedgeworth2c', 'Andalax', 'public', 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', null),
('schicchetto1i', 'Gembucket', 'public', 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', 'https://newsvine.com/justo.jsp'),
('nrehme1t', 'Fixflex', 'public', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 'https://nba.com/magna/ac/consequat.xml'),
('dfenech0', 'Sonair', 'private', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 'http://adobe.com/eu/est/congue/elementum/in.jpg'),
('ckirsz1o', 'Alpha', 'public', 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 'https://shutterfly.com/ac/leo/pellentesque/ultrices/mattis/odio.jsp'),
('corsayw', 'Bitwolf', 'public', null, null),
('ckirsz1o', 'Opela', 'public', null, 'http://slate.com/integer/aliquet/massa/id/lobortis.jsp'),
('mlumsdend', 'Tres-Zap', 'public', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', null),
('hcalveley27', 'Vagram', 'public', null, 'https://shutterfly.com/sit/amet/eros/suspendisse/accumsan/tortor.aspx'),
('rgirton2', 'Rank', 'private', 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', null),
('erenonu', 'Rank', 'private', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', null),
('eknowlson1g', 'Ronstring', 'public', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', null),
('bgalieroa', 'Bigtax', 'public', null, 'https://tinypic.com/risus/dapibus/augue/vel/accumsan/tellus/nisi.xml'),
('ccastiglione2r', 'Subin', 'public', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 'https://bizjournals.com/pede/malesuada/in/imperdiet.jsp'),
('dterry1l', 'Regrant', 'public', null, 'http://ow.ly/est/risus/auctor/sed/tristique/in/tempus.png'),
('dterry1l', 'Toughjoyfax', 'public', 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 'http://webs.com/massa/tempor.jpg'),
('dpartkya14', 'Stronghold', 'public', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 'https://nps.gov/eu/felis/fusce/posuere/felis/sed.aspx'),
('hcalveley27', 'Bitwolf', 'public', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 'http://ucsd.edu/justo/lacinia.jpg'),
('fhorsell15', 'Zoolab', 'public', 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 'https://psu.edu/consectetuer/eget.jpg'),
('rgirton2', 'Konklab', 'public', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 'http://miitbeian.gov.cn/nascetur.json'),
('wobbard19', 'Aerified', 'public', null, 'http://yellowbook.com/eget/semper/rutrum/nulla/nunc/purus.jsp'),
('dwrinchh', 'Bytecard', 'public', null, null),
('umcgerraghtyz', 'Ventosanzap', 'private', 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 'http://123-reg.co.uk/consectetuer.html'),
('ktidboldq', 'Flowdesk', 'public', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', null),
('frobilart23', 'Kanlam', 'public', 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede', 'http://xing.com/pretium/iaculis.js'),
('ahawke2o', 'Zoolab', 'private', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam', null),
('ahutchinges29', 'Biodex', 'public', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 'http://arstechnica.com/at/nunc/commodo/placerat/praesent/blandit/nam.jpg'),
('smammatt28', 'Solarbreeze', 'public', 'ligula nec sem duis aliquam convallis nunc proin at turpis', null),
('mhendrickxc', 'Matsoft', 'private', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 'https://biblegateway.com/dui/nec/nisi/volutpat/eleifend.js'),
('lwindus2j', 'Temp', 'private', 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', 'http://yolasite.com/aliquet/massa/id/lobortis.png'),
('lmclardie13', 'Flowdesk', 'public', null, 'http://virginia.edu/ut/nulla/sed.png'),
('sphillips7', 'Transcof', 'private', 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 'https://t-online.de/tempor/convallis/nulla/neque/libero/convallis/eget.jsp'),
('tleadsy', 'Duobam', 'private', null, 'http://oaic.gov.au/sapien/a.js'),
('abon16', 'Y-find', 'public', 'This is a new desc', 'https://v2.tailwindcss.com/docs/background-color'),
('dwrinchh', 'Alphazap', 'public', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', null),
('ddonavan1x', 'Voltsillam', 'private', null, 'http://google.ca/ut/blandit/non/interdum/in/ante.png'),
('ejennings26', 'Stim', 'private', null, 'http://quantcast.com/pede/malesuada/in/imperdiet.aspx'),
('lkittle4', 'Prodder', 'private', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc', null),
('ejennings26', 'Y-Solowarm', 'public', null, 'https://alibaba.com/felis/eu/sapien/cursus/vestibulum.png'),
('ckirsz1o', 'Ronstring', 'private', null, 'https://ifeng.com/vestibulum/proin/eu/mi.jsp'),
('coglesbee2f', 'Redhold', 'public', 'nulla elit ac nulla sed vel enim sit amet nunc viverra', 'https://washington.edu/ante.jsp'),
('schicchetto1i', 'Regrant', 'public', 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 'https://dion.ne.jp/scelerisque/quam/turpis/adipiscing.jpg'),
('abargeryj', 'Overhold', 'private', null, null),
('erenonu', 'Latlux', 'private', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 'http://blog.com/volutpat/convallis/morbi/odio/odio/elementum/eu.js'),
('avanyakin2n', 'Flexidy', 'private', 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'https://army.mil/sollicitudin/mi/sit/amet.json'),
('dfenech0', 'Pannier', 'public', null, 'https://netscape.com/erat/tortor/sollicitudin/mi/sit/amet.html'),
('eyabsley12', 'Aerified', 'private', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 'https://independent.co.uk/bibendum/imperdiet/nullam/orci/pede/venenatis.jsp'),
('kduckels2g', 'Trippledex', 'private', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 'http://dmoz.org/orci/luctus/et/ultrices/posuere/cubilia/curae.aspx'),
('umcgerraghtyz', 'Bamity', 'public', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', 'http://bloglovin.com/suscipit/a/feugiat/et.js'),
('gverrechia2b', 'Konklux', 'public', null, 'https://trellian.com/vestibulum/sit/amet.js'),
('aedgerton1n', 'Zoolab', 'public', null, null),
('mmaccomiskey11', 'Trippledex', 'private', 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 'http://hao123.com/in/faucibus/orci/luctus/et.png'),
('bdarlington1c', 'Zoolab', 'public', 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', 'https://washington.edu/convallis.html'),
('btidbold2l', 'Stronghold', 'public', null, 'https://etsy.com/facilisi/cras/non/velit/nec.js'),
('gsedgeworth2c', 'Latlux', 'public', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', 'http://wikimedia.org/lorem/vitae/mattis/nibh/ligula.jpg'),
('tkinsleyv', 'Gembucket', 'private', 'amet cursus id turpis integer aliquet massa id lobortis convallis', 'https://ustream.tv/vulputate/elementum/nullam.html'),
('jpaulitschkex', 'Mat Lam Tam', 'public', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget', 'http://dell.com/sit/amet/sapien/dignissim/vestibulum.png'),
('corsayw', 'Veribet', 'public', null, 'https://mlb.com/quam/pede/lobortis/ligula/sit/amet/eleifend.js'),
('aedgerton1n', 'Bamity', 'private', null, 'http://slashdot.org/lacus/morbi/sem/mauris/laoreet/ut.js'),
('bminer1z', 'Bitwolf', 'private', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://arizona.edu/turpis/elementum.aspx'),
('ahawke2o', 'It', 'private', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 'http://lycos.com/lorem/ipsum.jsp'),
('rgirton2', 'Bigtax', 'public', 'morbi a ipsum integer a nibh in quis justo maecenas', null),
('fcastellucci1f', 'Cookley', 'private', null, 'https://wikispaces.com/dapibus/nulla.js'),
('corsayw', 'Opela', 'private', null, 'https://wikia.com/ipsum/primis/in/faucibus.js'),
('avonb', 'Cookley', 'private', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', 'https://thetimes.co.uk/eget/eleifend/luctus/ultricies/eu/nibh/quisque.json'),
('ajakubowicz1j', 'Home Ing', 'public', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', null),
('hcalveley27', 'Namfix', 'private', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'https://mozilla.com/eu.html'),
('hcalveley27', 'Sub-Ex', 'private', 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', 'https://slashdot.org/vulputate/elementum/nullam.jsp'),
('gmaccaughen1s', 'Alphazap', 'public', 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 'http://themeforest.net/habitasse/platea/dictumst.js'),
('jpaulitschkex', 'Y-Solowarm', 'public', null, 'https://webnode.com/tempor/convallis/nulla/neque/libero/convallis/eget.png'),
('fgollin1e', 'Aerified', 'private', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 'http://tamu.edu/justo/sollicitudin/ut/suscipit/a/feugiat.json'),
('ddonavan1x', 'Otcom', 'private', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', 'http://goo.ne.jp/et/commodo/vulputate/justo.jpg'),
('orzehor1d', 'Keylex', 'private', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', 'http://utexas.edu/erat/nulla/tempus.xml'),
('jpaulitschkex', 'Trippledex', 'public', 'orci eget orci vehicula condimentum curabitur in libero ut massa', 'http://feedburner.com/vel/nisl/duis/ac/nibh/fusce.html'),
('dgraundisson2a', 'Home Ing', 'public', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', 'http://cam.ac.uk/neque/sapien/placerat/ante/nulla/justo/aliquam.js'),
('ntandy2m', 'Transcof', 'private', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', 'https://adobe.com/pretium/quis/lectus/suspendisse/potenti/in/eleifend.xml'),
('coglesbee2f', 'Zamit', 'public', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 'http://seattletimes.com/sapien/cum/sociis.jsp'),
('xfaraday2i', 'Cookley', 'private', 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', null),
('smammatt28', 'Temp', 'private', null, null),
('cteal2p', 'Ronstring', 'private', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 'https://ovh.net/eget/congue/eget/semper/rutrum/nulla.html'),
('astarbeckp', 'Home Ing', 'private', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 'https://pen.io/dui/nec/nisi.aspx'),
('cteal2p', 'Bamity', 'private', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 'http://dell.com/nascetur/ridiculus.png'),
('avonb', 'Job', 'private', 'in sagittis dui vel nisl duis ac nibh fusce lacus', 'https://mashable.com/lectus/in/quam.html'),
('coglesbee2f', 'Bamity', 'private', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', null),
('klanchbery1q', 'Zathin', 'public', 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', null),
('dgraundisson2a', 'Keylex', 'private', null, 'http://nsw.gov.au/ac/neque/duis/bibendum/morbi/non.xml'),
('mmelland1h', 'Mat Lam Tam', 'private', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', 'https://ftc.gov/quisque/porta/volutpat/erat/quisque/erat.jpg'),
('jsokale1v', 'Flexidy', 'private', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 'http://nih.gov/mattis/nibh/ligula/nec/sem/duis.xml'),
('abon16', 'Tres-Zap', 'public', null, 'https://kickstarter.com/pulvinar/sed/nisl/nunc/rhoncus.png'),
('nrehme1t', 'Gembucket', 'private', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 'https://diigo.com/sem.js'),
('abargeryj', 'Voyatouch', 'public', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 'http://uol.com.br/ac/enim/in/tempor/turpis.png'),
('ktidboldq', 'Biodex', 'public', null, null),
('ggaskampl', 'Prodder', 'public', 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', null),
('xfaraday2i', 'Zoolab', 'private', 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', null),
('hcalveley27', 'Flowdesk', 'private', 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', 'https://discuz.net/gravida.aspx'),
('ldriscoll24', 'Alphazap', 'private', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 'http://bigcartel.com/ipsum/praesent/blandit/lacinia/erat/vestibulum/sed.html'),
('lmclardie13', 'Matsoft', 'public', 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 'http://vistaprint.com/nisi/venenatis/tristique/fusce/congue.jpg'),
('cmittene', 'Flexidy', 'private', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', 'https://wsj.com/maecenas.jsp'),
('ahawke2o', 'Lotlux', 'private', null, null),
('jsokale1v', 'Aerified', 'public', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', null),
('avanyakin2n', 'Tempsoft', 'public', 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi', 'https://nih.gov/rutrum/rutrum/neque/aenean/auctor/gravida/sem.html'),
('dwrinchh', 'Biodex', 'private', null, 'http://ed.gov/est/et.xml'),
('sjillett1p', 'Matsoft', 'public', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec', 'https://auda.org.au/augue/quam/sollicitudin/vitae/consectetuer/eget.html'),
('dterry1l', 'Tres-Zap', 'public', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in', 'http://issuu.com/libero/nam.jpg'),
('gmidgley1a', 'Prodder', 'public', null, 'http://pcworld.com/placerat/ante/nulla/justo.aspx'),
('llanbertonis', 'Andalax', 'public', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', null),
('aedgerton1n', 'Konklux', 'private', null, 'http://etsy.com/augue/vestibulum/rutrum/rutrum/neque.jpg'),
('lwindus2j', 'Alphazap', 'public', null, 'https://ibm.com/pellentesque/at/nulla/suspendisse/potenti/cras.html'),
('lspringaten', 'Regrant', 'public', 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 'http://lycos.com/erat/fermentum.xml'),
('rlobe2h', 'Fixflex', 'public', null, null),
('osavine1u', 'Redhold', 'private', 'aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', 'http://weebly.com/lacinia/sapien.jsp'),
('tpriestm', 'Subin', 'private', null, 'https://hibu.com/justo/lacinia/eget/tincidunt/eget/tempus.jsp'),
('sjillett1p', 'Greenlam', 'public', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 'https://google.fr/rhoncus/dui/vel/sem/sed/sagittis.js'),
('phobble10', 'Zoolab', 'public', null, 'http://com.com/tellus/semper/interdum/mauris/ullamcorper/purus.png'),
('mlaugharne9', 'Tres-Zap', 'private', null, 'http://freewebs.com/amet/lobortis.json'),
('gmidgley1a', 'Hatity', 'public', null, 'https://hao123.com/velit/donec/diam/neque.html'),
('jpaulitschkex', 'Andalax', 'public', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', null),
('xfaraday2i', 'Fintone', 'private', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 'http://desdev.cn/rhoncus/mauris/enim/leo/rhoncus/sed/vestibulum.jpg'),
('dfenech0', 'Bitchip', 'public', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 'http://howstuffworks.com/aliquet/pulvinar.png'),
('nrehme1t', 'Zontrax', 'private', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 'http://netscape.com/tincidunt/lacus/at/velit/vivamus/vel.html'),
('ckirsz1o', 'Redhold', 'private', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo', null),
('cteal2p', 'Holdlamis', 'public', 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 'http://blogger.com/nulla/ut/erat/id/mauris/vulputate.html'),
('ghyslop1m', 'Bitchip', 'public', null, null),
('rlobe2h', 'Overhold', 'public', 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', null),
('dwrinchh', 'Transcof', 'private', 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 'https://mysql.com/facilisi/cras.jpg'),
('ktidboldq', 'Tampflex', 'private', null, 'https://cloudflare.com/nulla/mollis/molestie/lorem/quisque.xml'),
('ftaylersong', 'Viva', 'public', null, null),
('cteal2p', 'Ventosanzap', 'public', null, 'https://usatoday.com/duis.html'),
('fcastellucci1f', 'Kanlam', 'public', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', null),
('dfenech0', 'Overhold', 'public', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent', 'http://youku.com/ac/enim/in/tempor.json'),
('pstrood1r', 'Fix San', 'private', null, 'http://about.com/luctus/tincidunt/nulla/mollis.png'),
('mmaccomiskey11', 'Alphazap', 'public', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', null),
('fde2e', 'Veribet', 'public', 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 'http://diigo.com/sapien/placerat/ante/nulla/justo.js'),
('fcastellucci1f', 'Bytecard', 'public', 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', null),
('etampion1b', 'Konklux', 'public', null, null),
('xfaraday2i', 'Sub-Ex', 'public', null, null),
('jpaulitschkex', 'Stringtough', 'private', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', 'https://soup.io/magna.js'),
('ldriscoll24', 'Ventosanzap', 'public', 'mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', 'http://bandcamp.com/gravida/sem.jpg'),
('dfenech0', 'Cardguard', 'public', 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 'http://sun.com/quam/fringilla/rhoncus/mauris.html'),
('ldriscoll24', 'It', 'private', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', 'https://squidoo.com/a/ipsum/integer/a/nibh/in/quis.jpg'),
('ckirsz1o', 'Regrant', 'private', 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', null),
('ktidboldq', 'Lotstring', 'public', null, 'http://europa.eu/interdum/in.js'),
('ahawke2o', 'Alpha', 'public', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', 'http://fda.gov/magna/at/nunc/commodo/placerat/praesent/blandit.png'),
('gsedgeworth2c', 'Temp', 'private', 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', null),
('ftaylersong', 'Tin', 'public', null, 'https://usatoday.com/vel/augue/vestibulum.aspx'),
('fhorsell15', 'Trippledex', 'private', 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum', null),
('lkittle4', 'Sonsing', 'public', 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris', 'https://washingtonpost.com/habitasse/platea/dictumst/morbi/vestibulum.jpg'),
('sphillips7', 'Fix San', 'private', 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 'http://51.la/in/quis/justo/maecenas/rhoncus/aliquam.aspx'),
('fcastellucci1f', 'Cardify', 'public', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', 'http://huffingtonpost.com/duis.jpg'),
('avanyakin2n', 'Cardify', 'private', 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 'https://illinois.edu/pede/venenatis.aspx'),
('etampion1b', 'Flowdesk', 'private', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 'http://1688.com/quis/justo.png'),
('oalchinr', 'Kanlam', 'public', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 'http://mozilla.com/morbi/non/lectus/aliquam/sit.xml'),
('astarbeckp', 'Lotstring', 'public', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', null),
('tleadsy', 'Mat Lam Tam', 'private', 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'https://freewebs.com/diam/neque/vestibulum/eget.aspx'),
('smammatt28', 'Transcof', 'public', null, 'https://hubpages.com/in/hac/habitasse/platea.jsp'),
('rgirton2', 'Fixflex', 'public', null, null),
('umcgerraghtyz', 'Opela', 'private', 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 'https://google.ca/et/magnis/dis/parturient/montes/nascetur.js'),
('jtapper2q', 'Voyatouch', 'public', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 'https://nasa.gov/metus/aenean/fermentum.json'),
('hvoas18', 'Sonsing', 'private', 'ligula nec sem duis aliquam convallis nunc proin at turpis a', null),
('ghamper20', 'Zathin', 'private', 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 'http://whitehouse.gov/metus.xml'),
('llanbertonis', 'Prodder', 'public', null, 'https://ezinearticles.com/dui/proin.js'),
('phobble10', 'Alphazap', 'public', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 'https://buzzfeed.com/sapien/urna/pretium/nisl/ut.js'),
('smammatt28', 'Aerified', 'public', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', null),
('mbezzant17', 'Alpha', 'private', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', null),
('lspringaten', 'Subin', 'private', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 'https://loc.gov/hac/habitasse.json'),
('gmaccaughen1s', 'Stronghold', 'public', null, 'http://slideshare.net/eu/interdum/eu.jsp'),
('dfenech0', 'Tampflex', 'public', null, 'http://ed.gov/dui/luctus/rutrum/nulla/tellus/in/sagittis.html'),
('mmaccomiskey11', 'Flexidy', 'private', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'https://princeton.edu/a/nibh/in/quis/justo.aspx'),
('ashelley6', 'Lotstring', 'private', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 'https://thetimes.co.uk/tellus/nulla/ut/erat/id/mauris/vulputate.jpg'),
('klanchbery1q', 'Biodex', 'private', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', 'https://whitehouse.gov/nam.js'),
('mhendrickxc', 'Cookley', 'private', 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 'https://artisteer.com/natoque/penatibus.html'),
('mlaugharne9', 'Bigtax', 'public', null, 'https://wisc.edu/quisque/id/justo/sit/amet.jpg'),
('bminer1z', 'Flexidy', 'private', null, 'https://wordpress.com/curae/mauris/viverra/diam/vitae/quam.html'),
('erenonu', 'Transcof', 'public', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 'https://altervista.org/nisl/venenatis.json'),
('ktidboldq', 'Kanlam', 'private', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 'http://examiner.com/quisque.png'),
('bdarlington1c', 'Quo Lux', 'public', null, 'https://reuters.com/velit.js'),
('smammatt28', 'Keylex', 'public', null, null),
('fcastellucci1f', 'Hatity', 'private', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 'http://amazon.com/eleifend.js'),
('mgillino25', 'Hatity', 'public', 'eu massa donec dapibus duis at velit eu est congue elementum', null),
('gsedgeworth2c', 'Transcof', 'public', 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', null),
('cmittene', 'Span', 'private', null, null),
('abargeryj', 'Zaam-Dox', 'public', null, 'https://unesco.org/dis/parturient/montes/nascetur/ridiculus/mus.jsp');