DROP TABLE IF EXISTS Collaborators;

CREATE TABLE IF NOT EXISTS Collaborators (
	user VARCHAR(255) NOT NULL,
	owner VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY (user, owner, name),
	FOREIGN KEY (user) REFERENCES Users(username) ON DELETE CASCADE,
	FOREIGN KEY (owner, name) REFERENCES Repositories(owner, name) ON DELETE CASCADE
);

INSERT INTO Collaborators (user, owner, name) 
VALUES
('abargeryj', 'mmelland1h', 'Cardguard'),
('ghamper20', 'mmelland1h', 'Cardguard'),
('gverrechia2b', 'mmelland1h', 'Cardguard'),
('frobilart23', 'cmittene', 'Biodex'),
('bgalieroa', 'edumini2d', 'Bitchip'),
('ashelley6', 'shatt2k', 'Sub-Ex'),
('hvoas18', 'eyabsley12', 'Transcof'),
('ktidboldq', 'ashelley6', 'Kanlam'),
('ccastiglione2r', 'ashelley6', 'Kanlam'),
('ashelley6', 'dpartkya14', 'Stronghold'),
('rlobe2h', 'dpartkya14', 'Stronghold'),
('ghamper20', 'wobbard19', 'Aerified'),
('alabellt', 'umcgerraghtyz', 'Ventosanzap'),
('eknowlson1g', 'ahawke2o', 'Zoolab'),
('mmelland1h', 'ahutchinges29', 'Biodex'),
('gsedgeworth2c', 'ahutchinges29', 'Biodex'),
('noffai', 'abon16', 'Y-find'),
('mgillino25', 'dwrinchh', 'Alphazap'),
('rgirton2', 'ejennings26', 'Y-Solowarm'),
('hgolling1k', 'ckirsz1o', 'Ronstring'),
('jadamef', 'coglesbee2f', 'Redhold'),
('ftaylersong', 'umcgerraghtyz', 'Bamity'),
('alabellt', 'aedgerton1n', 'Zoolab'),
('kpelosi5', 'bdarlington1c', 'Zoolab'),
('mhendrickxc', 'gsedgeworth2c', 'Latlux'),
('smammatt28', 'gsedgeworth2c', 'Latlux'),
('ajakubowicz1j', 'corsayw', 'Veribet'),
('mmaccomiskey11', 'rgirton2', 'Bigtax'),
('tdanford1w', 'corsayw', 'Opela'),
('jadamef', 'jpaulitschkex', 'Y-Solowarm'),
('edumini2d', 'jpaulitschkex', 'Y-Solowarm'),
('klanchbery1q', 'ddonavan1x', 'Otcom'),
('noffai', 'orzehor1d', 'Keylex'),
('kpelosi5', 'dgraundisson2a', 'Home Ing'),
('jsokale1v', 'ntandy2m', 'Transcof'),
('corsayw', 'coglesbee2f', 'Zamit'),
('ntandy2m', 'coglesbee2f', 'Zamit'),
('etampion1b', 'smammatt28', 'Temp'),
('tdanford1w', 'cteal2p', 'Ronstring'),
('fcastellucci1f', 'astarbeckp', 'Home Ing'),
('eknowlson1g', 'avonb', 'Job'),
('etampion1b', 'coglesbee2f', 'Bamity'),
('jtapper2q', 'klanchbery1q', 'Zathin'),
('lmclardie13', 'dgraundisson2a', 'Keylex'),
('mlaugharne9', 'mmelland1h', 'Mat Lam Tam'),
('mmariyushkin21', 'mmelland1h', 'Mat Lam Tam'),
('rgirton2', 'abon16', 'Tres-Zap'),
('ckirsz1o', 'abon16', 'Tres-Zap'),
('kduckels2g', 'nrehme1t', 'Gembucket'),
('tkinsleyv', 'abargeryj', 'Voyatouch'),
('bkeeney8', 'ktidboldq', 'Biodex'),
('mmelland1h', 'ggaskampl', 'Prodder'),
('ddonavan1x', 'ggaskampl', 'Prodder'),
('oalchinr', 'lmclardie13', 'Matsoft'),
('ddonavan1x', 'ahawke2o', 'Lotlux'),
('bdarlington1c', 'avanyakin2n', 'Tempsoft'),
('hgolling1k', 'dwrinchh', 'Biodex'),
('gheffernon3', 'gmidgley1a', 'Prodder'),
('sjillett1p', 'aedgerton1n', 'Konklux'),
('ajakubowicz1j', 'rlobe2h', 'Fixflex'),
('xfaraday2i', 'sjillett1p', 'Greenlam'),
('cmittene', 'phobble10', 'Zoolab'),
('astarbeckp', 'phobble10', 'Zoolab'),
('tleadsy', 'phobble10', 'Zoolab'),
('ajakubowicz1j', 'phobble10', 'Zoolab'),
('ghyslop1m', 'phobble10', 'Zoolab'),
('dterry1l', 'mlaugharne9', 'Tres-Zap'),
('ggaskampl', 'jpaulitschkex', 'Andalax'),
('dfenech0', 'xfaraday2i', 'Fintone'),
('eknowlson1g', 'dfenech0', 'Bitchip'),
('ccastiglione2r', 'cteal2p', 'Holdlamis'),
('ajakubowicz1j', 'ghyslop1m', 'Bitchip'),
('rgirton2', 'rlobe2h', 'Overhold'),
('ghamper20', 'pstrood1r', 'Fix San'),
('xfaraday2i', 'fde2e', 'Veribet'),
('ashelley6', 'jpaulitschkex', 'Stringtough'),
('jpaulitschkex', 'jpaulitschkex', 'Stringtough'),
('fde2e', 'jpaulitschkex', 'Stringtough'),
('cmittene', 'dfenech0', 'Cardguard'),
('gheffernon3', 'ahawke2o', 'Alpha'),
('osavine1u', 'ahawke2o', 'Alpha'),
('coglesbee2f', 'fhorsell15', 'Trippledex'),
('tkinsleyv', 'etampion1b', 'Flowdesk'),
('phobble10', 'oalchinr', 'Kanlam'),
('avonb', 'ghamper20', 'Zathin'),
('umcgerraghtyz', 'ghamper20', 'Zathin'),
('dpartkya14', 'llanbertonis', 'Prodder'),
('fgollin1e', 'phobble10', 'Alphazap'),
('avanyakin2n', 'phobble10', 'Alphazap'),
('jpaulitschkex', 'lspringaten', 'Subin'),
('kduckels2g', 'lspringaten', 'Subin'),
('lcutridge22', 'dfenech0', 'Tampflex'),
('bgalieroa', 'mhendrickxc', 'Cookley'),
('lcutridge22', 'ktidboldq', 'Kanlam'),
('dgraundisson2a', 'bdarlington1c', 'Quo Lux'),
('abargeryj', 'fcastellucci1f', 'Hatity'),
('bdarlington1c', 'fcastellucci1f', 'Hatity'),
('dpartkya14', 'cmittene', 'Span'),
('klanchbery1q', 'cmittene', 'Span');