# Inspired from https://linuxhint.com/setup_git_http_server_docker/
version: "3.7"
services:
  git-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./repos:/var/www/git